services:
  - type: web
    name: dino-wallet-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dino-wallet-db
          property: connectionString
      - key: AUTO_SEED
        value: "true"

databases:
  - name: dino-wallet-db
    databaseName: wallet
    user: wallet
    plan: free
